import type { Product, CategoryItem } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 259.43,
    discountPercent: 24,
    ratingValue: 4.5,
    ratingCount: 142,
    isHot: true,
    colors: ["black", "blue", "red"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-air-max-270-react-sneakers.jpg",
  },
  {
    id: "2",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 259.43,
    discountPercent: 24,
    ratingValue: 4.2,
    ratingCount: 98,
    isHot: true,
    colors: ["red", "white"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-air-max-270-react-red-sneakers.jpg",
  },
  {
    id: "3",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 259.43,
    discountPercent: 24,
    ratingValue: 4.7,
    ratingCount: 203,
    isHot: true,
    colors: ["beige", "brown"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-air-max-270-react-beige-sneakers.jpg",
  },
  {
    id: "4",
    name: "Nike Air Max 270 React",
    price: 289.43,
    discountPrice: 249.43,
    discountPercent: 24,
    ratingValue: 4.3,
    ratingCount: 156,
    isHot: true,
    colors: ["blue", "white"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-air-max-270-react-blue-white-sneakers.jpg",
  },
  {
    id: "5",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 259.43,
    discountPercent: 24,
    ratingValue: 4.6,
    ratingCount: 187,
    isHot: true,
    colors: ["yellow", "black"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-air-max-270-react-yellow-black-sneakers.jpg",
  },
  {
    id: "6",
    name: "Nike Air Max 270 React",
    price: 299.43,
    discountPrice: 259.43,
    discountPercent: 24,
    ratingValue: 4.4,
    ratingCount: 134,
    isHot: true,
    colors: ["blue", "red"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-air-max-270-react-blue-red-sneakers.jpg",
  },
  {
    id: "7",
    name: "Adidas Ultraboost 22",
    price: 189.99,
    discountPrice: 149.99,
    discountPercent: 21,
    ratingValue: 4.8,
    ratingCount: 312,
    isHot: false,
    colors: ["black", "white"],
    category: "sneakers",
    brand: "Adidas",
    imageUrl: "/adidas-ultraboost-22-black-white-sneakers.jpg",
  },
  {
    id: "8",
    name: "Adidas Stan Smith",
    price: 89.99,
    ratingValue: 4.5,
    ratingCount: 456,
    isHot: false,
    colors: ["white", "green"],
    category: "sneakers",
    brand: "Adidas",
    imageUrl: "/adidas-stan-smith-white-green-sneakers.jpg",
  },
  {
    id: "9",
    name: "Vans Old Skool",
    price: 65.0,
    ratingValue: 4.3,
    ratingCount: 289,
    isHot: false,
    colors: ["black", "white"],
    category: "sneakers",
    brand: "Vans",
    imageUrl: "/vans-old-skool-black-white-sneakers.jpg",
  },
  {
    id: "10",
    name: "Converse Chuck Taylor All Star",
    price: 55.0,
    ratingValue: 4.2,
    ratingCount: 567,
    isHot: false,
    colors: ["red", "white"],
    category: "sneakers",
    brand: "All Stars",
    imageUrl: "/converse-chuck-taylor-all-star-red-sneakers.jpg",
  },
  {
    id: "11",
    name: "Nike Air Force 1",
    price: 110.0,
    ratingValue: 4.6,
    ratingCount: 423,
    isHot: false,
    colors: ["white"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-air-force-1-white-sneakers.jpg",
  },
  {
    id: "12",
    name: "Adidas Gazelle",
    price: 95.0,
    ratingValue: 4.4,
    ratingCount: 198,
    isHot: false,
    colors: ["blue", "white"],
    category: "sneakers",
    brand: "Adidas",
    imageUrl: "/adidas-gazelle-blue-white-sneakers.jpg",
  },
  {
    id: "13",
    name: "Puma Suede Classic",
    price: 75.0,
    ratingValue: 4.1,
    ratingCount: 234,
    isHot: false,
    colors: ["black", "red"],
    category: "sneakers",
    brand: "Puma",
    imageUrl: "/puma-suede-classic-black-red-sneakers.jpg",
  },
  {
    id: "14",
    name: "New Balance 574",
    price: 85.0,
    ratingValue: 4.3,
    ratingCount: 167,
    isHot: false,
    colors: ["gray", "white"],
    category: "sneakers",
    brand: "New Balance",
    imageUrl: "/new-balance-574-gray-white-sneakers.jpg",
  },
  {
    id: "15",
    name: "Reebok Classic Leather",
    price: 70.0,
    ratingValue: 4.0,
    ratingCount: 145,
    isHot: false,
    colors: ["white"],
    category: "sneakers",
    brand: "Reebok",
    imageUrl: "/reebok-classic-leather-white-sneakers.jpg",
  },
  {
    id: "16",
    name: "Nike React Element 55",
    price: 130.0,
    ratingValue: 4.5,
    ratingCount: 189,
    isHot: false,
    colors: ["black", "yellow"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-react-element-55-black-yellow-sneakers.jpg",
  },
  {
    id: "17",
    name: "Adidas NMD R1",
    price: 140.0,
    ratingValue: 4.7,
    ratingCount: 278,
    isHot: false,
    colors: ["black", "blue"],
    category: "sneakers",
    brand: "Adidas",
    imageUrl: "/adidas-nmd-r1-black-blue-sneakers.jpg",
  },
  {
    id: "18",
    name: "Vans Authentic",
    price: 50.0,
    ratingValue: 4.2,
    ratingCount: 312,
    isHot: false,
    colors: ["blue", "white"],
    category: "sneakers",
    brand: "Vans",
    imageUrl: "/vans-authentic-blue-white-sneakers.jpg",
  },
  {
    id: "19",
    name: "Converse One Star",
    price: 75.0,
    ratingValue: 4.1,
    ratingCount: 156,
    isHot: false,
    colors: ["green", "white"],
    category: "sneakers",
    brand: "All Stars",
    imageUrl: "/converse-one-star-green-white-sneakers.jpg",
  },
  {
    id: "20",
    name: "Nike Blazer Mid",
    price: 100.0,
    ratingValue: 4.4,
    ratingCount: 203,
    isHot: false,
    colors: ["white", "black"],
    category: "sneakers",
    brand: "Nike",
    imageUrl: "/nike-blazer-mid-white-black-sneakers.jpg",
  },
  {
    id: "21",
    name: "Adidas Superstar",
    price: 85.0,
    ratingValue: 4.6,
    ratingCount: 389,
    isHot: false,
    colors: ["white", "black"],
    category: "sneakers",
    brand: "Adidas",
    imageUrl: "/adidas-superstar-white-black-sneakers.jpg",
  },
  {
    id: "22",
    name: "Puma RS-X",
    price: 110.0,
    ratingValue: 4.2,
    ratingCount: 167,
    isHot: false,
    colors: ["white", "blue"],
    category: "sneakers",
    brand: "Puma",
    imageUrl: "/puma-rs-x-white-blue-sneakers.jpg",
  },
  {
    id: "23",
    name: "New Balance 990v5",
    price: 185.0,
    ratingValue: 4.8,
    ratingCount: 234,
    isHot: false,
    colors: ["gray"],
    category: "sneakers",
    brand: "New Balance",
    imageUrl: "/new-balance-990v5-gray-sneakers.jpg",
  },
  {
    id: "24",
    name: "Reebok Nano X",
    price: 130.0,
    ratingValue: 4.3,
    ratingCount: 145,
    isHot: false,
    colors: ["black", "red"],
    category: "sneakers",
    brand: "Reebok",
    imageUrl: "/reebok-nano-x-black-red-sneakers.jpg",
  },
  {
    id: "25",
    name: "Gucci GG Supreme Belt",
    price: 420.0,
    discountPrice: 378.0,
    discountPercent: 10,
    ratingValue: 4.8,
    ratingCount: 156,
    isHot: true,
    colors: ["brown", "black"],
    category: "belts",
    brand: "Gucci",
    imageUrl: "/gucci-gg-supreme-belt-brown.jpg",
  },
  {
    id: "26",
    name: "Louis Vuitton Damier Belt",
    price: 520.0,
    ratingValue: 4.9,
    ratingCount: 203,
    isHot: true,
    colors: ["brown", "black"],
    category: "belts",
    brand: "Louis Vuitton",
    imageUrl: "/louis-vuitton-damier-belt.jpg",
  },
  {
    id: "27",
    name: "Hermès H Belt",
    price: 890.0,
    ratingValue: 5.0,
    ratingCount: 89,
    isHot: false,
    colors: ["black", "brown"],
    category: "belts",
    brand: "Hermès",
    imageUrl: "/hermes-h-belt-black.jpg",
  },
  {
    id: "28",
    name: "Coach Signature C Belt",
    price: 175.0,
    discountPrice: 140.0,
    discountPercent: 20,
    ratingValue: 4.3,
    ratingCount: 267,
    isHot: false,
    colors: ["brown", "black"],
    category: "belts",
    brand: "Coach",
    imageUrl: "/coach-signature-c-belt.jpg",
  },
  {
    id: "29",
    name: "Versace Medusa Belt",
    price: 395.0,
    ratingValue: 4.6,
    ratingCount: 134,
    isHot: false,
    colors: ["black", "gold"],
    category: "belts",
    brand: "Versace",
    imageUrl: "/versace-medusa-belt-black.jpg",
  },
  {
    id: "30",
    name: "Calvin Klein Classic Belt",
    price: 65.0,
    discountPrice: 52.0,
    discountPercent: 20,
    ratingValue: 4.1,
    ratingCount: 345,
    isHot: false,
    colors: ["black", "brown"],
    category: "belts",
    brand: "Calvin Klein",
    imageUrl: "/calvin-klein-classic-belt.jpg",
  },
  {
    id: "31",
    name: "Tommy Hilfiger Logo Belt",
    price: 45.0,
    ratingValue: 3.9,
    ratingCount: 198,
    isHot: false,
    colors: ["black", "brown"],
    category: "belts",
    brand: "Tommy Hilfiger",
    imageUrl: "/tommy-hilfiger-logo-belt.jpg",
  },
  {
    id: "32",
    name: "Hugo Boss Leather Belt",
    price: 125.0,
    ratingValue: 4.4,
    ratingCount: 156,
    isHot: false,
    colors: ["black", "brown"],
    category: "belts",
    brand: "Hugo Boss",
    imageUrl: "/hugo-boss-leather-belt.jpg",
  },
  {
    id: "33",
    name: "Louis Vuitton Neverfull MM",
    price: 1650.0,
    ratingValue: 4.9,
    ratingCount: 312,
    isHot: true,
    colors: ["brown", "black"],
    category: "bags",
    brand: "Louis Vuitton",
    imageUrl: "/louis-vuitton-neverfull-mm.jpg",
  },
  {
    id: "34",
    name: "Gucci GG Marmont Bag",
    price: 2100.0,
    discountPrice: 1890.0,
    discountPercent: 10,
    ratingValue: 4.8,
    ratingCount: 189,
    isHot: true,
    colors: ["black", "red", "pink"],
    category: "bags",
    brand: "Gucci",
    imageUrl: "/gucci-gg-marmont-bag.jpg",
  },
  {
    id: "35",
    name: "Chanel Classic Flap Bag",
    price: 6200.0,
    ratingValue: 5.0,
    ratingCount: 156,
    isHot: true,
    colors: ["black", "beige"],
    category: "bags",
    brand: "Chanel",
    imageUrl: "/chanel-classic-flap-bag.jpg",
  },
  {
    id: "36",
    name: "Hermès Birkin 30",
    price: 12500.0,
    ratingValue: 5.0,
    ratingCount: 67,
    isHot: false,
    colors: ["black", "brown", "red"],
    category: "bags",
    brand: "Hermès",
    imageUrl: "/hermes-birkin-30-black.jpg",
  },
  {
    id: "37",
    name: "Coach Pillow Tabby Bag",
    price: 395.0,
    discountPrice: 316.0,
    discountPercent: 20,
    ratingValue: 4.5,
    ratingCount: 234,
    isHot: false,
    colors: ["black", "white", "pink"],
    category: "bags",
    brand: "Coach",
    imageUrl: "/coach-pillow-tabby-bag.jpg",
  },
  {
    id: "38",
    name: "Michael Kors Jet Set Travel Tote",
    price: 228.0,
    discountPrice: 159.6,
    discountPercent: 30,
    ratingValue: 4.2,
    ratingCount: 456,
    isHot: false,
    colors: ["black", "brown", "white"],
    category: "bags",
    brand: "Michael Kors",
    imageUrl: "/michael-kors-jet-set-travel-tote.jpg",
  },
  {
    id: "39",
    name: "Prada Re-Edition 2005",
    price: 1250.0,
    ratingValue: 4.7,
    ratingCount: 123,
    isHot: false,
    colors: ["black", "white", "pink"],
    category: "bags",
    brand: "Prada",
    imageUrl: "/prada-re-edition-2005.jpg",
  },
  {
    id: "40",
    name: "Marc Jacobs The Tote Bag",
    price: 195.0,
    discountPrice: 156.0,
    discountPercent: 20,
    ratingValue: 4.3,
    ratingCount: 298,
    isHot: false,
    colors: ["black", "white", "beige"],
    category: "bags",
    brand: "Marc Jacobs",
    imageUrl: "/marc-jacobs-the-tote-bag.jpg",
  },
  {
    id: "41",
    name: "Balenciaga City Bag",
    price: 1850.0,
    ratingValue: 4.6,
    ratingCount: 167,
    isHot: false,
    colors: ["black", "white", "red"],
    category: "bags",
    brand: "Balenciaga",
    imageUrl: "/balenciaga-city-bag.jpg",
  },
  {
    id: "42",
    name: "Bottega Veneta Jodie Bag",
    price: 2750.0,
    ratingValue: 4.8,
    ratingCount: 89,
    isHot: false,
    colors: ["black", "brown", "green"],
    category: "bags",
    brand: "Bottega Veneta",
    imageUrl: "/bottega-veneta-jodie-bag.jpg",
  },
]

export const categories: CategoryItem[] = [
  { name: "sneakers", count: 24 },
  { name: "belts", count: 8 },
  { name: "bags", count: 10 },
  { name: "Nike", count: 48 },
  { name: "Airmax", count: 48 },
  { name: "Nike", count: 14 },
  { name: "Adidas", count: 15 },
  { name: "Vans", count: 23 },
  { name: "All Stars", count: 1 },
  { name: "Adidas", count: 95 },
]

export const brands = [
  "Nike", "Adidas", "Vans", "All Stars", "Puma", "New Balance", "Reebok",
  "Gucci", "Louis Vuitton", "Hermès", "Coach", "Versace", "Calvin Klein", "Tommy Hilfiger", "Hugo Boss",
  "Chanel", "Prada", "Michael Kors", "Marc Jacobs", "Balenciaga", "Bottega Veneta"
]

export const colors = [
  { name: "black", value: "#000000" },
  { name: "white", value: "#ffffff" },
  { name: "red", value: "#ef4444" },
  { name: "blue", value: "#3b82f6" },
  { name: "green", value: "#22c55e" },
  { name: "yellow", value: "#eab308" },
  { name: "gray", value: "#6b7280" },
  { name: "beige", value: "#d2b48c" },
  { name: "brown", value: "#a16207" },
  { name: "pink", value: "#ec4899" },
  { name: "gold", value: "#fbbf24" },
]
